### ISSUE TITLE
Get Wordpress to run

### ISSUE THREAD

**Issue by jankapunkt** [eduhack/hp5-wordpress-docker#4]

**Comment by jankapunkt** [comment]
https://codex.wordpress.org/Installing_WordPress#Famous_5-Minute_Installation

**Comment by jankapunkt** [comment]
+ MariaDB / NGINX

**Comment by aakalaew** [comment]
Wordpress is now running on my machine. To access Wordpress you need to connect to your localhost via Browser.

**Comment by aakalaew** [comment]
To start Wordpress you need to create the wordpress container with the following command in your Terminal
`docker run -e WORDPRESS_DB_PASSWORD=<password> --name wordpress --link wordpressdb:mysql -p 80:80 -v "$PWD/html":/var/www/html -d wordpress`

**Comment by aakalaew** [comment]
In the previous command, you need to choose a port that isn't already used by another process or you'll get an error like this 

> docker: Error response from daemon: driver failed programming external connectivity on endpoint wordpress (e79753a726dba733b5a768d1b5499f8e5e32ab3d94531c896d407272747a6914): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

**Comment by aakalaew** [comment]
If everything went right you'll see in your browser the installation window for wordpress. 

![image](https://user-images.githubusercontent.com/35196389/50282006-9c245680-0451-11e9-91ca-c9a15ab21dff.png)
